### ISSUE TITLE
Crashing when opening new buffer

### ISSUE THREAD

**Issue by ruiiiijiiiiang** [alanfortlink/animatedbg.nvim#2]
When I open neovim with snack.nvim's [dashboard](https://github.com/folke/snacks.nvim/blob/main/docs/terminal.md), the background animation correctly starts playing but once I open a file in a new buffer, it crashes with the following message:

```
Error executing vim.schedule lua callback: ...im/lazy/animatedbg.nvim/lua/animatedbg-nvim/renderer.lua:11: Invalid buffer id: 1
stack traceback:
	[C]: in function 'nvim_buf_get_lines'
	...im/lazy/animatedbg.nvim/lua/animatedbg-nvim/renderer.lua:11: in function 'get_row_content'
	...im/lazy/animatedbg.nvim/lua/animatedbg-nvim/renderer.lua:42: in function 'render'
	...im/lazy/animatedbg.nvim/lua/animatedbg-nvim/executor.lua:84: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by alanfortlink** [comment]
@ruiiiijiiiiang I couldn't really reproduce it, but I've had that issue before when the buf is deleted.  I added a check and now it should only call `nvim_buf_get_lines` when the buffer is still valid. Let me know if this fixes the issue :)

**Comment by ruiiiijiiiiang** [comment]
@alanfortlink I can confirm this has been fixed with the latest patch. Thank you so much!
